import { useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Check, ClipboardCheck, FileText, Send, ShieldCheck } from 'lucide-react'
import { AssetThumb } from './Assets'
import { adopted, dateLabel, downloadBlob, now, safeURL, snapshot, uid, type Asset, type DeliveryItem, type Handoff, type Project, type PushRecord, type Selection } from './model'
import { Badge, Button, card, Empty, Field, input, Modal, textarea } from './ui'

import { MaterialSummary } from './MaterialLinks'

export function DeliveryView({ project, onOpen, onAssets, onChange, onHandoff, onPush, onFeedback }: { project: Project; onOpen: (id: string) => void; onAssets: () => void; onChange: (id: string, patch: Partial<Asset>, message: string) => void; onHandoff: (h: Handoff) => void; onPush: (p: PushRecord) => void; onFeedback: (id: string, feedback: string) => void }) {
  const [modal, setModal] = useState<'handoff' | 'push' | null>(null), [record, setRecord] = useState<PushRecord | Handoff | null>(null)
  const selected = project.assets.filter(a => a.delivery), styles = selected.filter(a => a.kind === '款式设计'), docs = selected.filter(a => a.kind !== '款式设计')
  function exportManifest() {
    downloadBlob(new Blob([JSON.stringify({ project: project.name, exportedAt: now(), notice: '当前工作清单，未经内部确认，不代表已流转 PLM。文件内容请从资产中另行下载。', items: selected.map(snapshot) }, null, 2)], { type: 'application/json' }), `${project.name}-交付清单.json`)
  }
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[18px] font-semibold">项目交付</h2><p className="text-[12px] text-ink-3 mt-1">从资产中择优汇集，确认后交给样衣开发。</p></div><Button primary disabled={!styles.some(a => a.selection === '保留')} onClick={() => setModal('handoff')}><ShieldCheck size={15} />内部确认与交接</Button></div>
    <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-2xl bg-pri-soft/40 border border-pri-line"><div className="text-[12px] text-ink-2 leading-6"><span className="font-medium text-ink">{selected.length} 项交付内容 · {styles.length} 个款式 · {styles.filter(a => a.selection === '保留').length} 个保留</span><br />客户反馈供内部决策参考；选入交付、保留款式均不等于最终确认。</div><div className="flex gap-2"><Button onClick={onAssets}>添加交付内容</Button><Button aria-label="下载交付清单" title="下载清单（不含文件本体）" disabled={!selected.length} onClick={exportManifest} className="px-3"><ArrowDownToLine size={15} /></Button></div></div>
    <section><div className="flex items-center justify-between mb-4"><h3 className="text-[15px] font-semibold">项目文档与材料 <span className="text-mut font-normal text-[12px]">{docs.length}</span></h3></div>{!docs.length ? <p className="text-[12px] text-ink-3 py-4">可按需加入 Brief、趋势报告、企划 PPT 和面辅料资料，不强制齐全。</p> : <div className={`${card} divide-y divide-line-soft`}>{docs.map(a => <div key={a.id} className="px-4 py-3 flex items-center gap-3"><FileText size={18} className="text-ink-3 shrink-0" /><button onClick={() => onOpen(a.id)} className="flex-1 min-w-0 text-left truncate hover:text-pri" title={a.name}>{a.name}</button><span className="text-[11px] text-mut">V{a.revisions.findIndex(r => r.id === a.adopted) + 1}</span><button className="text-[12px] text-ink-3 hover:text-pri" onClick={() => onChange(a.id, { delivery: false }, `从交付移除：${a.name}`)}>移除</button></div>)}</div>}</section>
    <section><div className="flex items-center justify-between mb-4"><h3 className="text-[15px] font-semibold">款式与内部选款 <span className="text-mut font-normal text-[12px]">{styles.length}</span></h3></div>{!styles.length ? <div className={card}><Empty title="还没有交付款式" text="在资产中上传款式设计，再选入交付。" /></div> : <div className="space-y-3">{styles.map(a => <div key={a.id} className={`${card} p-4 flex items-start gap-4`}><button onClick={() => onOpen(a.id)} className="w-28 shrink-0 rounded-xl overflow-hidden hidden sm:block"><AssetThumb key={adopted(a).id} asset={a} large /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-3"><button onClick={() => onOpen(a.id)} title={a.name} className="font-medium text-left hover:text-pri truncate">{a.name} <ArrowUpRight size={12} className="inline" /></button><select aria-label={`${a.name}内部选款`} className={`${input} !w-auto h-8 text-[12px]`} value={a.selection} onChange={e => onChange(a.id, { selection: e.target.value as Selection }, `内部选款：${a.name} → ${e.target.value}`)}>{['待选', '保留', '备选', '修改', '淘汰'].map(s => <option key={s}>{s}</option>)}</select></div><p className="text-[11px] text-mut mt-2">已采用 V{a.revisions.findIndex(r => r.id === a.adopted) + 1}</p><p className="text-[12px] text-ink-3 mt-3 leading-6 whitespace-pre-wrap line-clamp-2">{a.material || '尚未补充面辅料与样衣开发说明'}</p><MaterialSummary links={a.materials} /><div className="flex flex-wrap gap-4 mt-3 text-[12px]"><button className="text-pri" onClick={() => onOpen(a.id)}>查看 / 补充开发资料</button>{a.cloud && safeURL(a.cloud) && <a href={safeURL(a.cloud)!} rel="noopener noreferrer" target="_blank" className="text-pri">3D 样衣 ↗</a>}<button className="text-ink-3 ml-auto" onClick={() => onChange(a.id, { delivery: false }, `从交付移除：${a.name}`)}>移除</button></div></div></div>)}</div>}</section>
    <section className={`${card} p-5`}><div className="flex justify-between items-center mb-2 gap-3"><h3 className="font-semibold text-[15px]">客户沟通</h3><Button disabled={!styles.length || !project.customers.length} onClick={() => setModal('push')}><Send size={14} />新建推款记录</Button></div><p className="text-[12px] text-ink-3 mb-4">{!project.customers.length ? '自主开发项目暂未关联客户；关联后可按客户建立推款记录。' : '按客户记录推荐款式与反馈，保留当时的资料版本。此原型不会向客户发送消息。'}</p>{!project.pushes.length ? <p className="text-[12px] text-mut py-3">暂无沟通记录</p> : <div className="space-y-2">{project.pushes.map(p => <button key={p.id} onClick={() => setRecord(p)} className="w-full text-left rounded-xl bg-fill-2 p-4 flex items-center gap-3"><div className="flex-1 min-w-0"><p className="font-medium truncate">{p.customer}</p><p className="text-[11px] text-ink-3 mt-1">{p.items.length} 款 · {dateLabel(p.date)} · {p.feedback ? '已记录反馈' : '待反馈'}</p></div><ArrowUpRight size={15} /></button>)}</div>}</section>
    <section className={`${card} p-5`}><h3 className="font-semibold text-[15px] flex items-center gap-2"><ClipboardCheck size={17} className="text-ink-3" />内部确认与交接记录</h3><p className="text-[12px] text-ink-3 mt-2 mb-4">仅内部最终确认后形成固定快照。PLM 接口未接入，本页仅演示交接，不创建真实开发单。</p>{!project.handoffs.length ? <p className="text-[12px] text-mut py-3">尚未形成内部确认记录</p> : <div className="space-y-2">{project.handoffs.map((h, i) => <button key={h.id} onClick={() => setRecord(h)} className="w-full flex items-center gap-3 text-left p-4 rounded-xl bg-fill-2"><Check size={16} className="text-pri" /><div className="flex-1"><p>第 {project.handoffs.length - i} 次内部确认 · {h.items.length} 项</p><p className="text-[11px] text-ink-3 mt-1">{h.confirmedBy} · {dateLabel(h.date)}</p></div><Badge>模拟交接</Badge></button>)}</div>}</section>
    {modal && <DeliveryForm mode={modal} project={project} onClose={() => setModal(null)} onSave={(items, value) => { if (modal === 'handoff') onHandoff({ id: uid(), date: now(), confirmedBy: value, items }); else onPush({ id: uid(), date: now(), customer: value, customerId: project.customerIds?.[project.customers.indexOf(value)], items, feedback: '' }); setModal(null) }} />}
    {record && <RecordDetail record={record} onClose={() => setRecord(null)} onFeedback={value => { onFeedback(record.id, value); setRecord({ ...record, feedback: value } as PushRecord) }} />}
  </div>
}

function DeliveryForm({ mode, project, onClose, onSave }: { mode: 'handoff' | 'push'; project: Project; onClose: () => void; onSave: (items: DeliveryItem[], value: string) => void }) {
  const candidates = project.assets.filter(a => a.delivery && (mode === 'push' ? a.kind === '款式设计' : a.kind !== '款式设计' || a.selection === '保留'))
  const [ids, setIds] = useState(candidates.map(a => a.id)), [value, setValue] = useState(mode === 'push' ? project.customers[0] ?? '' : project.owner), [confirmed, setConfirmed] = useState(false)
  const selected = candidates.filter(a => ids.includes(a.id)), hasStyle = selected.some(a => a.kind === '款式设计')
  return <Modal title={mode === 'push' ? '新建客户推款记录' : '内部确认与交接'} description={mode === 'push' ? '选择本次向该客户推荐的款式，保存沟通记录，不实际发送。' : '仅“保留”款可进入样衣开发交接。请选择本次最终确认的内容，形成不可随资产修改而变化的快照。'} onClose={onClose}><div className="space-y-5"><Field label={mode === 'push' ? '关联客户' : '内部确认人'}>{mode === 'push' ? <select className={input} value={value} onChange={e => setValue(e.target.value)}>{project.customers.map(c => <option key={c}>{c}</option>)}</select> : <input className={input} value={value} maxLength={40} onChange={e => setValue(e.target.value)} />}</Field><div className="space-y-2 max-h-64 overflow-auto">{candidates.map(a => <label key={a.id} className="flex items-center gap-3 p-3 rounded-xl border border-line"><input type="checkbox" className="accent-pri" checked={ids.includes(a.id)} onChange={e => setIds(e.target.checked ? [...ids, a.id] : ids.filter(id => id !== a.id))} /><span className="flex-1 min-w-0 truncate" title={a.name}>{a.name}</span><span className="text-[11px] text-ink-3">V{a.revisions.findIndex(r => r.id === a.adopted) + 1}</span></label>)}</div>
    {mode === 'handoff' && <><p className="text-[12px] text-ink-3 leading-6">请核查面辅料、样衣说明与待确认事项。这里是原型确认门槛，不代表真实审批权限校验或 PLM 接收成功。</p><label className="flex items-start gap-3 p-3 bg-pri-soft/40 rounded-xl"><input type="checkbox" className="accent-pri mt-1" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span className="leading-6">我已完成内部核查，确认以上所选内容可用于样衣开发，并生成模拟交接记录。</span></label></>}
    <div className="flex justify-end gap-2"><Button onClick={onClose}>取消</Button><Button primary disabled={!hasStyle || !value.trim() || (mode === 'handoff' && !confirmed)} onClick={() => onSave(selected.map(snapshot), value.trim())}>{mode === 'push' ? '保存推款记录' : '确认并模拟交接'}</Button></div></div></Modal>
}

function RecordDetail({ record, onClose, onFeedback }: { record: PushRecord | Handoff; onClose: () => void; onFeedback: (s: string) => void }) {
  const isPush = 'customer' in record
  const [feedback, setFeedback] = useState(isPush ? record.feedback : '')
  return <Modal title={isPush ? `${record.customer} · 推款记录` : '内部确认快照'} description={`${dateLabel(record.date)} · ${isPush ? '客户反馈不会改变内部确认状态' : `确认人：${record.confirmedBy} · 模拟交接，未发送 PLM`}`} onClose={onClose}><div className="space-y-4"><div className="space-y-2">{record.items.map(item => <div key={item.assetId} className="p-3 border border-line rounded-xl"><p className="font-medium">{item.name}</p><p className="text-[11px] text-ink-3 mt-2">{item.revision.name} · {dateLabel(item.revision.date)}</p>{item.material && <p className="mt-2 text-[12px] whitespace-pre-wrap text-ink-2">{item.material}</p>}<MaterialSummary links={item.materials} />{item.cloud && safeURL(item.cloud) && <a href={safeURL(item.cloud)!} target="_blank" rel="noopener noreferrer" className="text-pri text-[12px] block mt-2">查看当时的 3D 样衣链接 ↗</a>}</div>)}</div>{isPush && <><Field label="客户反馈"><textarea className={textarea} rows={4} value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="记录客户对具体款式、面料和修改方向的反馈…" /></Field><Button onClick={() => onFeedback(feedback)}>保存反馈</Button></>}<Button onClick={() => downloadBlob(new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' }), `${isPush ? '推款' : '内部确认'}-${record.id.slice(0, 8)}.json`)}><ArrowDownToLine size={14} />下载记录快照</Button></div></Modal>
}
