import { useState } from 'react'
import { ArrowLeft, Check, Columns3, ExternalLink, Pencil } from 'lucide-react'
import { AssetThumb } from './Assets'
import { now, safeURL, uid, type Asset, type Project, type Selection, type Task } from './model'
import { Badge, Button, card, Empty, Modal, textarea } from './ui'
import type { CaseUpdate } from './CaseWorkbench'

export function InternalSelection({ project, onBack, onOpen, onChange, onUpdate }: { project: Project; onBack: () => void; onOpen: (id: string) => void; onChange: (id: string, patch: Partial<Asset>, text: string) => boolean; onUpdate: CaseUpdate }) {
  const [filter, setFilter] = useState('全部'), [selected, setSelected] = useState<string[]>([]), [compare, setCompare] = useState(false), [notice, setNotice] = useState('')
  const styles = project.assets.filter(a => a.kind === '款式设计')
  const picked = styles.filter(a => selected.includes(a.id))
  function modify(a: Asset, note: string) {
    const task: Task = { id: uid(), name: `修改：${a.name}`, type: '款式设计', assignee: project.members?.find(m => m.role.includes('设计'))?.name ?? project.owner, reviewer: project.owner, status: '待开始', updated: now(), refs: [{ assetId: a.id, revisionId: a.adopted, name: a.name }], context: { goal: project.goal, customers: project.customers, brands: project.brands, skills: ['款式设计与改款'], experts: ['服装设计专家'], connectors: project.connectors }, messages: [{ id: uid(), role: 'user', text: `内部选款修改意见：${note}\n修改后上传新版本，重新核查再选入交付。`, date: now() }], history: [{ date: now(), text: '由内部选款意见创建修改任务' }] }
    if (onUpdate(p => ({ ...p, tasks: [task, ...p.tasks], assets: p.assets.map(x => x.id === a.id ? { ...x, selection: '修改', selectionNote: note, selectionBy: p.owner, delivery: false } : x) }), `选款意见生成修改任务：${a.name}`)) setNotice('修改任务已创建，在“任务”中继续处理；该款暂时移出交付。')
  }
  return <div className="space-y-5" data-testid="internal-selection"><button onClick={onBack} className="flex items-center gap-2 text-[12px] text-ink-3 hover:text-pri"><ArrowLeft size={14} />全部资产</button><div className="flex items-start justify-between flex-wrap gap-3"><div><h2 className="text-[20px] font-semibold">内部选款</h2><p className="text-[12px] text-ink-3 mt-2">看图、比较、记意见。只有人工保留的款式进入最终交接。</p></div><Button disabled={picked.length < 2} onClick={() => setCompare(true)}><Columns3 size={15} />并排比较 {picked.length ? `(${picked.length})` : ''}</Button></div>
    <div className="flex gap-2 flex-wrap">{['全部', '待选', '保留', '备选', '修改', '淘汰'].map(s => <button key={s} onClick={() => setFilter(s)} className={`px-3 py-2 rounded-full text-[12px] ${filter === s ? 'bg-pri-soft text-pri' : 'bg-fill text-ink-3'}`}>{s} · {s === '全部' ? styles.length : styles.filter(a => a.selection === s).length}</button>)}</div>
    <div className="rounded-2xl bg-pri-soft/40 border border-pri-line p-4 flex flex-wrap justify-between items-center gap-3"><p className="text-[12px] text-ink-2">已保留 {styles.filter(a => a.selection === '保留').length} 款 · 选款不是最终批准</p><Button primary disabled={!styles.some(a => a.selection === '保留' && !a.delivery)} onClick={() => { if (onUpdate(p => ({ ...p, assets: p.assets.map(a => a.kind === '款式设计' && a.selection === '保留' ? { ...a, delivery: true } : a) }), '将内部保留款选入交付')) setNotice('已将保留款加入交付，请到“交付”提交内部审核。') }}><Check size={14} />将保留款选入交付</Button></div>
    {!styles.length ? <Empty title="先准备款式设计" text="在设计任务中归档图片，或上传人工设计，款式就会出现在这里。" /> : <div className="grid md:grid-cols-2 min-[1600px]:grid-cols-3 gap-4">{styles.filter(a => filter === '全部' || a.selection === filter).map(a => <div key={a.id} className={`${card} overflow-hidden`}><div className="p-4 flex justify-between items-center"><label className="text-[12px] flex items-center gap-2"><input aria-label={`比较${a.name}`} type="checkbox" className="accent-pri" checked={selected.includes(a.id)} disabled={!selected.includes(a.id) && picked.length >= 3} onChange={e => setSelected(e.target.checked ? [...selected, a.id] : selected.filter(id => id !== a.id))} />加入比较</label><Badge tone={a.selection === '保留' ? 'green' : a.selection === '修改' ? 'orange' : 'muted'}>{a.selection}</Badge></div><button className="w-full [&>div]:!h-64" onClick={() => onOpen(a.id)}><AssetThumb asset={a} large /></button><div className="p-4"><h3 className="text-[15px] font-medium">{a.name}</h3><p className="text-[11px] text-ink-3 mt-2">采用 V{a.revisions.findIndex(r => r.id === a.adopted) + 1} · {a.materials?.length ?? 0} 个关联材料</p><p className="text-[12px] text-ink-3 leading-6 mt-3 line-clamp-2">{a.material || '尚未补充开发说明'}</p><div className="mt-3 flex flex-wrap gap-3 text-[12px]"><button className="text-pri" onClick={() => onOpen(a.id)}>开发资料 / 修订版本</button>{a.cloud && safeURL(a.cloud) ? <a href={safeURL(a.cloud)!} target="_blank" rel="noopener noreferrer" className="text-pri inline-flex gap-1 items-center">Cloud 3D<ExternalLink size={12} /></a> : <button className="text-ink-3" onClick={() => onOpen(a.id)}>绑定 Cloud 3D 链接</button>}</div><StyleDecision asset={a} onChange={patch => onChange(a.id, { ...patch, selectionBy: project.owner, ...(patch.selection && patch.selection !== '保留' ? { delivery: false } : {}) }, `内部选款：${a.name} → ${patch.selection ?? '更新意见'}`)} onModify={note => modify(a, note)} /></div></div>)}</div>}
    {notice && <p role="status" className="bg-pri-soft text-pri p-3 rounded-xl text-[12px]">{notice}</p>}
    {compare && <Modal wide title="款式并排比较" description="最多比较三款，重点核查搭配、材料和开发风险；点击详情可查看大图。" onClose={() => setCompare(false)}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{picked.map(a => <div key={a.id} className="min-w-0 rounded-2xl bg-fill-2 p-3"><AssetThumb asset={a} large /><h3 className="font-medium mt-3">{a.name}</h3><p className="text-[11px] text-pri mt-2">{a.selection} · V{a.revisions.findIndex(r => r.id === a.adopted) + 1}</p><p className="text-[12px] text-ink-3 leading-6 mt-3 whitespace-pre-wrap">{a.material}</p><p className="text-[12px] mt-3">主料：{a.materials?.map(m => m.name).join('、') || '待选择'}</p><p className="text-[12px] text-ink-3 mt-3">意见：{a.selectionNote || '待填写'}</p><Button className="mt-3" onClick={() => { setCompare(false); onOpen(a.id) }}>查看详情</Button></div>)}</div></Modal>}
  </div>
}

function StyleDecision({ asset, onChange, onModify }: { asset: Asset; onChange: (patch: Partial<Asset>) => boolean; onModify: (note: string) => void }) {
  const [note, setNote] = useState(asset.selectionNote ?? '')
  return <div className="mt-4 pt-4 border-t border-line-soft"><div className="flex gap-2 flex-wrap">{(['保留', '备选', '修改', '淘汰'] as Selection[]).map(s => <button key={s} onClick={() => onChange({ selection: s, selectionNote: note })} aria-pressed={asset.selection === s} className={`rounded-full border text-[12px] px-3 py-1.5 ${asset.selection === s ? 'bg-pri-soft border-pri-line text-pri' : 'border-line text-ink-3 hover:text-pri'}`}>{s}</button>)}</div><textarea aria-label={`${asset.name}选款意见`} className={`${textarea} mt-3 !text-[12px]`} rows={2} value={note} onChange={e => setNote(e.target.value)} placeholder="为什么保留，或哪里需要修改？" /><div className="flex items-center gap-2 flex-wrap mt-2"><Button disabled={note === (asset.selectionNote ?? '')} onClick={() => onChange({ selectionNote: note })}>保存意见</Button><Button disabled={!note.trim()} onClick={() => onModify(note.trim())}><Pencil size={12} />生成修改任务</Button></div></div>
}
