import { capabilityById, capabilityLabel } from './capabilities'
import { makeAsset, now, uid, type Asset, type Task, type SearchSet, type DocumentKind } from './model'
import { Badge, Button, card } from './ui'

export function InvocationCards({ task, onOutput, onOpenAsset, onSearch, onDocument }: { onDocument: (kind: DocumentKind, invocationId: string) => void; onSearch: (kind: SearchSet['kind'], invocationId: string) => void; task: Task; onOutput: (t: Task, a: Asset) => void; onOpenAsset: (id: string) => void }) {
  function demonstrate(invocation: NonNullable<Task['invocations']>[number]) {
    const c = invocation.capability
    const text = `# ${c.name} · 工作底稿\n\n> 原型工作底稿，不是 AI 分析、真实检索或设计结果。尚未连接执行服务，以下内容来自调用配置，专业结论待人工填写。\n\n## 本次要求\n${invocation.instruction}\n\n## 项目背景（任务创建时）\n${task.context.goal || '未填写'}\n\n## 引用资料\n${invocation.refs.map(r => `- ${r.name}`).join('\n') || '尚未引用资料'}\n\n## 预期产出\n${c.output}\n\n## 工作成果\n待补充；可下载后编辑，再上传修订版本。\n\n## 人工确认\n${c.review}\n\n## 拟使用数据源\n${c.sources.join('、') || '本次提供的资料'}（未连接）\n`
    const asset = makeAsset(`${c.name} · 工作底稿`, '项目文档', { id: uid(), name: `${c.name}-工作底稿.md`, mime: 'text/markdown', date: now(), text }, '任务产出')
    asset.taskId = task.id
    onOutput({ ...task, status: '待人工处理', updated: now(), invocations: task.invocations?.map(i => i.id === invocation.id ? { ...i, status: '已演示', outputId: asset.id } : i), messages: [...task.messages, { id: uid(), role: 'assistant', date: now(), text: `【原型演示】「${c.name}」工作底稿已归档。仅汇集调用要求和预期成果，不含真实 AI 分析。可下载补充内容，再上传修订。` }] }, asset)
  }
  if (!task.invocations?.length) return null
  return <section aria-label="能力调用记录" className="space-y-3"><h3 className="font-medium">本任务的能力调用</h3>{task.invocations.map(i => <div key={i.id} className={`${card} p-4 space-y-3`}><div className="flex flex-wrap gap-2 items-center"><Badge tone="blue">{capabilityLabel[i.capability.kind]}</Badge><h4 className="font-medium flex-1">{i.capability.name}</h4><Badge>{i.status === '已配置' ? '待接入执行服务' : '已生成演示底稿'}</Badge></div><p className="text-[12px] leading-6 whitespace-pre-wrap break-words">{i.instruction}</p>{i.capability.members && <p className="text-[12px] text-ink-3">协作成员：{i.capability.members.map(id => capabilityById(id)?.name ?? id).join('、')}</p>}<details className="text-[12px] text-ink-3"><summary className="cursor-pointer">输入与预期产出 · {i.refs.length} 份资料</summary><div className="mt-2 leading-6 space-y-2"><p>引用：{i.refs.map(r => r.name).join('、') || '无附件，按本次要求配置'}</p><p>产出：{i.capability.output}</p><p>人工确认：{i.capability.review}</p><p>拟接数据：{i.capability.sources.join('、') || '本次提供资料'} · 尚未执行</p></div></details>{(i.capability.id === 'odm-style-search' || i.capability.id === 'odm-material-search' || i.capability.skills?.some(id => id === 'odm-style-search' || id === 'odm-material-search')) && <Button onClick={() => onSearch(i.capability.id.includes('material') ? '面辅料' : '款式', i.id)}>打开检索结果工作区</Button>}{([{ id: 'odm-brief', kind: 'Brief 拆解' }, { id: 'odm-trend-report', kind: '趋势报告' }, { id: 'odm-planning-ppt', kind: '企划 PPT' }] as { id: string; kind: DocumentKind }[]).filter(d => i.capability.id === d.id || i.capability.skills?.includes(d.id)).map(d => <Button key={d.id} onClick={() => onDocument(d.kind, i.id)}>打开{d.kind}工作稿</Button>)}{i.outputId ? <Button onClick={() => onOpenAsset(i.outputId!)}>查看工作底稿</Button> : <Button onClick={() => demonstrate(i)}>生成演示工作底稿</Button>}</div>)}</section>
}
