import { useState } from 'react'
import { adopted, type Asset, type MaterialLink, type Project } from './model'
import { Badge, Button, Field, input } from './ui'

export function MaterialLinks({ project, asset, onSave }: { project: Project; asset: Asset; onSave: (links: MaterialLink[]) => boolean }) {
  const [links, setLinks] = useState<MaterialLink[]>(() => structuredClone(asset.materials ?? [])), [candidate, setCandidate] = useState(''), [message, setMessage] = useState('')
  const candidates = project.assets.filter(a => a.kind === '面辅料' && !links.some(l => l.assetId === a.id))
  function patch(id: string, value: Partial<MaterialLink>) { setLinks(rows => rows.map(r => r.assetId === id ? { ...r, ...value } : r)); setMessage('尚未保存') }
  return <section className="border-t border-line mt-5 pt-5 space-y-4" aria-label="款式关联面辅料"><div><h3 className="font-semibold text-[15px]">选用面辅料</h3><p className="text-[12px] text-ink-3 leading-6 mt-1">关联项目中已归档的候选料，保存选用时的资料版本。采购条件与实物仍需核实。</p></div><div className="flex gap-3 items-end"><div className="flex-1 min-w-0"><Field label="从项目面辅料中选择"><select value={candidate} onChange={e => setCandidate(e.target.value)} className={input}><option value="">{candidates.length ? '选择面辅料' : '请先搜料归档，或上传面辅料资料'}</option>{candidates.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field></div><Button disabled={!candidates.some(a => a.id === candidate)} onClick={() => { const a = candidates.find(a => a.id === candidate); if (!a) return; setLinks([...links, { assetId: a.id, name: a.name, revision: structuredClone(adopted(a)), role: '主料', usage: '', supplier: '', notes: '' }]); setCandidate(''); setMessage('尚未保存') }}>添加关联</Button></div>
    {!links.length && <p className="text-[12px] text-ink-3">暂无选料，不会自动采用 AI 推荐的候选。</p>}
    {links.map(l => <div key={l.assetId} className="rounded-2xl border border-line p-4 space-y-3"><div className="flex gap-3 items-center"><h4 className="font-medium flex-1 break-words">{l.name}</h4><Badge>{l.role}</Badge><button className="text-[12px] text-ink-3 hover:text-pri" onClick={() => { setLinks(links.filter(x => x.assetId !== l.assetId)); setMessage('尚未保存') }}>移除关联</button></div><p className="text-[11px] text-ink-3">引用文件：{l.revision.name} · {new Date(l.revision.date).toLocaleDateString('zh-CN')}</p>{project.assets.find(a => a.id === l.assetId)?.adopted !== l.revision.id && <p className="text-[12px] text-warn">源资料版本已变化，本次选料仍保留原版本；如需更新，请移除后重新关联。</p>}<div className="grid sm:grid-cols-2 gap-3"><Field label={`${l.name} · 用料角色`}><select className={input} value={l.role} onChange={e => patch(l.assetId, { role: e.target.value as MaterialLink['role'] })}><option>主料</option><option>辅料</option><option>备选料</option></select></Field><Field label={`${l.name} · 使用部位 / 用量`}><input className={input} value={l.usage} maxLength={200} onChange={e => patch(l.assetId, { usage: e.target.value })} placeholder="例如：衣身；用量待确认" /></Field><Field label={`${l.name} · 供应商`}><input className={input} value={l.supplier} maxLength={200} onChange={e => patch(l.assetId, { supplier: e.target.value })} placeholder="未核实可留空" /></Field><Field label={`${l.name} · 规格与核实备注`}><input className={input} value={l.notes} maxLength={1000} onChange={e => patch(l.assetId, { notes: e.target.value })} placeholder="成分、克重、色号、采购条件等" /></Field></div></div>)}
    <div className="flex justify-between items-center gap-3"><span role="status" className="text-[12px] text-ink-3">{message}</span><Button onClick={() => { if (onSave(links)) setMessage('选料关联已保存；历史交付快照保持不变') }}>保存选料关联</Button></div>
  </section>
}

export function MaterialSummary({ links }: { links?: MaterialLink[] }) {
  if (!links?.length) return null
  return <div className="space-y-2 mt-3 text-[12px]">{links.map(l => <div key={l.assetId} className="rounded-xl bg-fill-2 p-3"><p className="font-medium">{l.role} · {l.name}</p><p className="text-ink-3 mt-1 leading-6">{l.usage || '部位 / 用量待确认'} · {l.supplier || '供应商待核实'}{l.notes ? ` · ${l.notes}` : ''}</p></div>)}</div>
}
