import { Link } from 'react-router'
import { ArrowRight, FileText, FolderCheck, MessageSquare, Pencil } from 'lucide-react'
import { useState } from 'react'
import { CASE_NOTICE } from './zaraDemo'
import type { CaseUpdate } from './CaseWorkbench'
import { statusTone } from './lifecycleModel'
import { dateLabel, type Project, type Tab } from './model'
import { profileIds, profileURL } from './directory'
import { Badge, Button, card, input } from './ui'

export function ProjectOverview({ project, onTab, onTask, onNewTask, onEdit, onUpdate }: { project: Project; onTab: (tab: Tab) => void; onTask: (id: string) => void; onNewTask: () => void; onEdit: () => void; onUpdate: CaseUpdate }) {
  const [comment, setComment] = useState('')
  const waiting = project.tasks.filter(t => ['待审核', '退回修改', '待人工处理'].includes(t.status))
  return <div className="space-y-6">
    <section className={card + " p-6"}><div className="flex justify-between items-center mb-3"><p className="text-[12px] text-mut">开发目标</p><button onClick={onEdit} className="text-[12px] text-ink-3 hover:text-pri">编辑</button></div><p className="text-[16px] leading-8 max-w-3xl">{project.goal || "从客户需求或一个设计想法开始。"}</p><div className="flex gap-3 mt-6"><Button primary onClick={onNewTask}>发起任务<ArrowRight size={14} /></Button><Button onClick={() => onTab("资产")}>查看资料</Button></div></section>
    <div className="grid grid-cols-3 gap-3">{[{ label: '项目任务', count: project.tasks.length, tab: '任务' as Tab, icon: MessageSquare }, { label: '资料与成果', count: project.assets.length, tab: '资产' as Tab, icon: FileText }, { label: '交付内容', count: project.assets.filter(a => a.delivery).length, tab: '交付' as Tab, icon: FolderCheck }].map(c => <button key={c.label} onClick={() => onTab(c.tab)} className={`${card} p-4 text-left hover:border-pri/40`}><div className="flex justify-between items-center"><p className="text-[12px] text-ink-3">{c.label}</p><c.icon size={15} className="text-mut" /></div><p className="text-[26px] font-semibold mt-3">{c.count}</p></button>)}</div>

    {!!waiting.length && <section><div className="flex justify-between gap-3 mb-3"><h2 className="font-semibold text-[15px]">需要你处理</h2><button onClick={() => onTab('任务')} className="text-[12px] text-pri">全部任务 →</button></div><div className="space-y-2">{waiting.slice(0, 3).map(t => <button key={t.id} onClick={() => onTask(t.id)} className={`${card} p-4 flex items-center gap-3 w-full text-left`}><span className="flex-1 min-w-0 truncate">{t.name}</span><Badge tone={statusTone(t.status)}>{t.status}</Badge><ArrowRight size={14} /></button>)}</div></section>}
    <details className={`${card} p-5`}><summary className="cursor-pointer font-medium">项目背景与关联档案 <span className="text-[12px] text-ink-3 font-normal ml-2">客户、品牌</span></summary><div className="mt-4 space-y-4">{project.caseId && <p className="text-[11px] text-ink-3">{CASE_NOTICE}</p>}<div className="grid sm:grid-cols-2 gap-4">{(['customer', 'brand'] as const).map(kind => <div key={kind}><p className="text-[11px] text-mut mb-2">{kind === 'customer' ? '客户' : '品牌'}</p>{(kind === 'customer' ? project.customers : project.brands).map((name, i) => <Link key={name} className="text-pri block text-[12px] py-1" to={profileURL(kind, profileIds(project, kind)[i])}>{name} ↗</Link>)}</div>)}</div><Button onClick={onEdit}><Pencil size={13} />编辑项目信息</Button></div></details>
    {project.requirements && <details className={`${card} p-5`}><summary className="cursor-pointer font-medium">已确认的开发需求</summary><div className="space-y-3 mt-4">{project.requirements.sections.map(s => <div key={s.id}><h3 className="text-[12px] font-medium">{s.title}</h3><p className="text-[12px] text-ink-3 leading-6 mt-1 whitespace-pre-wrap">{s.body}</p></div>)}</div></details>}
    <details className={`${card} p-5`}><summary className="cursor-pointer text-[12px] text-ink-3">项目管理</summary><div className="flex items-center justify-between gap-3 flex-wrap mt-4"><h2 className="font-semibold text-[13px]">状态与成员</h2><span className="text-[12px] text-mut">{project.members?.length || 1} 位成员 · 右上角邀请加入</span></div><div className="flex flex-wrap items-center gap-3 mt-4"><Badge tone={statusTone(project.status)}>{project.status}</Badge><p className="text-[12px] text-ink-3">{project.owner} 负责 · {project.developmentMode ?? (project.customers.length ? '客户开发' : '自主开发')}</p><div className="ml-auto flex flex-wrap gap-2">{project.status === '待启动' && <Button primary onClick={() => onUpdate(p => ({ ...p, status: '进行中' }), '人工启动项目')}>启动项目</Button>}{['进行中', '修改中', '待内部确认'].includes(project.status) && <Button onClick={() => onTab('交付')}>查看交付 / 内部确认</Button>}{project.status !== '已归档' && <Button onClick={() => onUpdate(p => ({ ...p, status: '已归档' }), '项目已归档（可恢复）')}>归档项目</Button>}{project.status === '已归档' && <Button onClick={() => onUpdate(p => ({ ...p, status: p.handoffs.length ? '已交接' : '进行中' }), '恢复项目')}>恢复项目</Button>}</div></div><p className="text-[11px] text-mut mt-3 leading-5">待启动 → 进行中 → 待内部确认 → 已交接；退回进入修改中，可重新提交。归档只收起项目，不删除资料。原型不校验人员权限。</p></details>
    <details className={`${card} p-5`}><summary className="cursor-pointer font-medium">项目动态与留言 <span className="text-[11px] text-mut font-normal ml-2">{project.activities.length} 条记录</span></summary><form className="flex gap-2 my-4" onSubmit={e => { e.preventDefault(); if (comment.trim() && onUpdate(p => p, `我：${comment.trim()}`)) setComment('') }}><input className={input} aria-label="项目留言" value={comment} onChange={e => setComment(e.target.value)} placeholder="记录讨论结论…" /><Button type="submit" disabled={!comment.trim()}>发布</Button></form><div className="space-y-4 max-h-80 overflow-auto">{project.activities.map(a => <div key={a.id}><p className="text-[12px] leading-6">{a.text}</p><p className="text-[10px] text-mut">{dateLabel(a.date)}</p></div>)}</div></details>
  </div>
}
