import { useState } from 'react'
import { ArrowLeft, ExternalLink, Search } from 'lucide-react'
import { AssetThumb } from './Assets'
import { adopted, makeAsset, now, safeURL, storeFile, uid, type Asset, type Project, type SearchSet, type Task } from './model'
import { searchLocal } from './searchLibrary'
import { Badge, Button, card, Field, input, Modal, textarea } from './ui'

export function SearchWorkspace({ project, task, initialKind, invocationId, onSave, onCollect, onCanvas, onClose }: { project: Project; task: Task; initialKind: SearchSet['kind']; invocationId?: string; onSave: (s: SearchSet) => boolean; onCollect: (assets: Asset[]) => boolean; onCanvas: (assets: Asset[]) => void; onClose: () => void }) {
  const latest = task.searches?.find(s => s.kind === initialKind && (!invocationId || s.invocationId === invocationId))
  const [kind, setKind] = useState(initialKind), [query, setQuery] = useState(latest?.query ?? ''), [scope, setScope] = useState<SearchSet['scope']>(latest?.scope ?? '内部')
  const [activeId, setActiveId] = useState<string | undefined>(latest?.id), [reference, setReference] = useState(latest?.reference)
  const [manual, setManual] = useState(false), [compare, setCompare] = useState(false), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const active = task.searches?.find(s => s.id === activeId)
  const selected = active?.results.filter(a => active.selected.includes(a.id)) ?? []
  function search() {
    const s: SearchSet = { id: uid(), date: now(), kind, query: query.trim(), scope, reference, invocationId, selected: [], results: scope === '外部' ? [] : searchLocal(project, kind, query) }
    if (onSave(s)) { setActiveId(s.id); setMessage(scope === '外部' ? '外部搜索服务尚未连接，可手动收录已有参考。' : '已完成本地关键词筛选；尚未执行图像相似度检索。') }
  }
  async function uploadReference(file: File) { setBusy(true); try { if (!file.type.startsWith('image/')) throw new Error('参考图请选择图片文件'); setReference(await storeFile(file)); setMessage('参考图已暂存；点击检索后随结果集保存，不自动归入项目资产。') } catch (e) { setMessage((e as Error).message) } finally { setBusy(false) } }
  function choose(a: Asset) { if (active) onSave({ ...active, selected: active.selected.includes(a.id) ? active.selected.filter(id => id !== a.id) : [...active.selected, a.id] }) }
  return <div className="space-y-5" data-testid="search-workspace"><button onClick={onClose} className="flex gap-2 items-center text-[12px] text-ink-3 hover:text-pri"><ArrowLeft size={14} />返回任务对话</button><div><h2 className="text-[20px] font-semibold">搜款搜料工作区</h2><p className="text-[12px] text-ink-3 mt-2">结果先跟随当前任务保存，选中的资料才归档到项目。</p></div>
    <form className={`${card} p-5 space-y-4`} onSubmit={e => { e.preventDefault(); search() }}><div className="grid sm:grid-cols-2 gap-4"><Field label="检索对象"><select className={input} value={kind} onChange={e => setKind(e.target.value as SearchSet['kind'])}><option>款式</option><option>面辅料</option></select></Field><Field label="数据范围"><select className={input} value={scope} onChange={e => setScope(e.target.value as SearchSet['scope'])}><option>内部</option><option>外部</option><option>全部</option></select></Field></div><Field label="检索描述"><input className={input} value={query} maxLength={500} onChange={e => setQuery(e.target.value)} placeholder="例如：风衣，或面料关键词；留空浏览本地候选" /></Field><div className="flex flex-wrap gap-3 items-center"><label className="text-pri text-[12px] cursor-pointer border border-dashed border-pri/40 rounded-xl px-4 py-3">{reference ? `参考图：${reference.name}` : '上传参考图（可选）'}<input type="file" aria-label="搜索参考图" accept="image/*" className="sr-only" disabled={busy} onChange={e => { const f = e.target.files?.[0]; if (f) void uploadReference(f); e.target.value = '' }} /></label>{reference && <Button onClick={() => setReference(undefined)}>移除参考图</Button>}<Button primary type="submit" disabled={busy} className="sm:ml-auto"><Search size={14} />{scope === '外部' ? '建立外部检索任务' : '检索本地候选'}</Button></div><p className="text-[11px] text-ink-3 leading-6">当前仅按名称、说明进行关键词筛选，包含明确标注的厂商示例；图片仅保存为检索条件，不输出虚构的相似度。外部实时检索与内部正式数据库未接入。</p></form>
    {!!task.searches?.length && <Field label="历史结果集"><select className={input} value={activeId ?? ''} onChange={e => { const s = task.searches?.find(x => x.id === e.target.value); if (s) { setActiveId(s.id); setKind(s.kind); setQuery(s.query); setScope(s.scope); setReference(s.reference); setMessage('') } }}><option value="" disabled>选择结果集</option>{task.searches?.map(s => <option key={s.id} value={s.id}>{s.kind} · {s.scope} · {s.query || '浏览候选'} · {new Date(s.date).toLocaleTimeString('zh-CN')} · {s.results.length} 项</option>)}</select></Field>}
    {message && <p role="status" className="rounded-xl bg-fill p-3 text-[12px] text-ink-2">{message}</p>}
    {active && <><div className="flex flex-wrap gap-3 items-center"><h3 className="font-semibold flex-1">{active.kind}候选 · {active.results.length} 项</h3><Button onClick={() => setManual(true)}>手动收录外部参考</Button></div>{!active.results.length ? <div className={`${card} p-8 text-center text-ink-3 text-[12px]`}>{active.scope === '外部' ? '未连接外部检索服务。可上传已经获取的参考，记录真实来源。' : '没有匹配候选，可调整关键词或手动收录参考。'}</div> : <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{active.results.map(a => <div key={a.id} className={`${card} overflow-hidden ${active.selected.includes(a.id) ? 'border-pri' : ''}`}><AssetThumb key={adopted(a).id} asset={a} large /><div className="p-4 space-y-3"><label className="flex gap-2 items-start cursor-pointer"><input type="checkbox" className="accent-pri mt-1" checked={active.selected.includes(a.id)} onChange={() => choose(a)} /><span className="font-medium break-words">{a.name}</span></label><div className="flex flex-wrap gap-2"><Badge>{a.provenance?.scope ?? '内部'}</Badge>{a.provenance?.demo && <Badge>示例数据</Badge>}</div><p className="text-[11px] text-ink-3 leading-6">来源：{a.provenance?.provider}<br />{a.provenance?.scope === '外部' ? '手动收录，未经 AI 匹配' : '名称 / 说明命中或本地浏览候选'}</p>{a.provenance?.url && safeURL(a.provenance.url) && <a className="text-[12px] text-pri inline-flex items-center gap-1" href={safeURL(a.provenance.url)!} target="_blank" rel="noopener noreferrer">查看来源<ExternalLink size={12} /></a>}</div></div>)}</div>}
    <div className="sticky bottom-0 bg-panel border border-line rounded-2xl p-4 flex flex-wrap gap-3 items-center"><span className="text-[12px] mr-auto">已选 {selected.length} 项</span><Button disabled={selected.length < 2 || selected.length > 4} onClick={() => setCompare(true)}>对比（2–4 项）</Button><Button disabled={!selected.length} onClick={() => { if (onCollect(selected)) setMessage('已择优归入项目资产；重复候选不会重复创建。') }}>归档所选</Button><Button primary disabled={!selected.some(a => adopted(a).mime.startsWith('image/'))} onClick={() => onCanvas(selected.filter(a => adopted(a).mime.startsWith('image/')))}>加入设计画布</Button></div></>}
    {manual && active && <ExternalReference kind={active.kind} onClose={() => setManual(false)} onSave={a => { if (onSave({ ...active, results: [...active.results, a] })) { setManual(false); return true }; return false }} />}
    {compare && <Modal wide title="候选对比" description="展示已有资料，不推断未提供的成本、供应条件或相似度。" onClose={() => setCompare(false)}><div className="grid sm:grid-cols-2 gap-4">{selected.map(a => <div key={a.id} className={`${card} p-4 space-y-3`}><AssetThumb asset={a} large /><h3 className="font-medium">{a.name}</h3><p className="text-[12px] text-ink-3">{a.provenance?.provider}</p><p className="text-[12px] leading-6">{a.material || '规格、价格、工艺与交期：尚未提供，待人工确认。'}</p></div>)}</div></Modal>}
  </div>
}

function ExternalReference({ kind, onSave, onClose }: { kind: SearchSet['kind']; onSave: (a: Asset) => boolean; onClose: () => void }) {
  const [name, setName] = useState(''), [provider, setProvider] = useState(''), [url, setUrl] = useState(''), [notes, setNotes] = useState(''), [file, setFile] = useState<File>(), [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function save() { if (!file) return; setBusy(true); setError(''); try { const link = safeURL(url); if (link === null) throw new Error('来源链接只能是有效的 http / https 地址'); const a = makeAsset(name.trim(), kind === '面辅料' ? '面辅料' : '参考资料', await storeFile(file), '资料收集'); a.provenance = { key: uid(), scope: '外部', provider: provider.trim(), url: link || undefined, collectedAt: now() }; a.material = notes.trim(); onSave(a) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <Modal title="手动收录外部参考" description="只上传有权使用的文件。先加入任务结果集，是否长期归档由你决定。" onClose={() => { if (!busy) onClose() }}><div className="space-y-4"><Field label="参考名称 *"><input className={input} value={name} maxLength={100} onChange={e => setName(e.target.value)} /></Field><Field label="来源平台 / 供应商 *"><input className={input} value={provider} maxLength={100} onChange={e => setProvider(e.target.value)} /></Field><Field label="来源链接（可选）"><input className={input} value={url} onChange={e => setUrl(e.target.value)} /></Field><Field label="规格与备注"><textarea className={textarea} value={notes} maxLength={3000} onChange={e => setNotes(e.target.value)} /></Field><Field label="参考文件 *"><input type="file" disabled={busy} onChange={e => setFile(e.target.files?.[0])} /></Field>{error && <p role="alert" className="text-err">{error}</p>}<div className="flex justify-end gap-2"><Button onClick={onClose} disabled={busy}>取消</Button><Button primary disabled={busy || !file || !name.trim() || !provider.trim()} onClick={() => void save()}>{busy ? '保存中…' : '加入结果集'}</Button></div></div></Modal>
}
