import { useState } from 'react'
import { ArrowLeft, ArrowUp, ArrowUpRight, Check, FileText, MessageSquare, Plus, Sparkles } from 'lucide-react'
import coat from '@/assets/brandlib/coat1.png'
import { adopted, dateLabel, makeAsset, now, TASK_TYPES, uid, type Asset, type Project, type Task, type SearchSet, type DocumentKind, type WorkDocument } from './model'
import { Badge, Button, card, Empty, Field, input, Modal, SearchBox, textarea } from './ui'
import { profileSummary, useDirectory } from './directory'
import { ProfilePicker, ProfileSnapshots } from './ProfileReferences'
import { CapabilityPicker } from './CapabilityPicker'
import { InvocationCards } from './InvocationCards'
import { SearchWorkspace } from './SearchWorkspace'
import { DemoTaskFlow } from './DemoTaskFlow'
import { demoRequest } from './model'
import { ProjectCanvas } from './ProjectCanvas'
import { DocumentWorkspace } from './DocumentWorkspace'
import { CaseWorkbench, type CaseUpdate } from './CaseWorkbench'
import { TaskLifecycle } from './Lifecycle'
import { TASK_STATUSES, statusTone } from './lifecycleModel'
import type { Tab } from './model'

export function TaskForm({ project, reference, onSave, onClose }: { project: Project; reference?: Asset; onSave: (task: Task) => void; onClose: () => void }) {
  const { records } = useDirectory()
  const [profiles, setProfiles] = useState<string[]>([]), [files, setFiles] = useState<string[]>([])
  const [name, setName] = useState(''), [prompt, setPrompt] = useState(''), [type, setType] = useState('自由任务'), [refs, setRefs] = useState<string[]>(reference ? [reference.id] : [])
  return <Modal title="新建任务" description="一个项目可以发起多个任务对话。自动带入项目目标与配置，按需引用资产。" onClose={onClose}><form className="space-y-5" onSubmit={e => {
    e.preventDefault(); if (!prompt.trim()) return
    onSave({ id: uid(), name: name.trim() || prompt.trim().slice(0, 36), type, status: '进行中', updated: now(), refs: project.assets.filter(a => refs.includes(a.id)).map(a => ({ assetId: a.id, revisionId: a.adopted, name: `${a.name} · V${a.revisions.findIndex(r => r.id === a.adopted) + 1}` })), context: { requirements: project.requirements ? structuredClone(project.requirements) : undefined, goal: project.goal, customers: [...project.customers], brands: [...project.brands], skills: [...project.skills], experts: [...project.experts], teams: [...(project.teams ?? [])], connectors: [...project.connectors], profiles: records.filter(p => profiles.includes(p.id) || p.documents.some(d => files.includes(d.id))).map(p => ({ id: p.id, kind: p.kind, name: p.name, summary: profiles.includes(p.id) ? profileSummary(p) : '', documents: structuredClone(p.documents.filter(d => files.includes(d.id))), capturedAt: now() })) }, messages: [{ id: uid(), role: 'user', text: prompt.trim(), date: now() }, { id: uid(), role: 'assistant', text: '【原型演示】任务已建立，并记录项目背景与引用资料。当前尚未接入 AI 服务；可以补充讨论、演示示例产出，或将线下完成的成果上传归档。', date: now() }] })
  }}><Field label="任务类型"><select className={input} value={type} onChange={e => setType(e.target.value)}>{TASK_TYPES.map(t => <option key={t}>{t}</option>)}</select></Field><Field label="任务名称（可选）"><input className={input} value={name} maxLength={80} onChange={e => setName(e.target.value)} placeholder="不填则使用首条需求作为任务名称" /></Field><Field label="这次需要完成什么？ *"><textarea autoFocus required className={textarea} rows={4} maxLength={10000} value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="例如：结合客户 Brief 和趋势资料，整理这次风衣系列的 3 个开发方向。" /></Field>
    <details className="border border-line rounded-xl p-3" open={!!reference}><summary className="cursor-pointer">引用项目资产 <span className="text-mut">已选 {refs.length}</span></summary><div className="space-y-2 max-h-40 overflow-auto mt-3">{!project.assets.length && <p className="text-ink-3 text-[12px]">项目还没有资产，可稍后补充。</p>}{project.assets.map(a => <label key={a.id} className="flex gap-2 items-center"><input type="checkbox" className="accent-pri" checked={refs.includes(a.id)} onChange={e => setRefs(e.target.checked ? [...refs, a.id] : refs.filter(id => id !== a.id))} /><span className="truncate" title={a.name}>{a.name}</span></label>)}</div></details>
    <ProfilePicker project={project} selected={profiles} files={files} onSelected={setProfiles} onFiles={setFiles} />
    <p className="text-[11px] text-ink-3">配置了 {project.experts.length} 位专家、{project.teams?.length ?? 0} 个专家团、{project.skills.length} 个技能、{project.connectors.length} 个拟接入数据源。创建时保存快照；可在对话中按需调用能力。</p><div className="flex justify-end gap-2"><Button onClick={onClose}>取消</Button><Button primary type="submit" disabled={!prompt.trim()}>创建任务</Button></div></form></Modal>
}

function sampleOutput(task: Task, p: Project): Asset {
  if (task.type === '款式设计' || task.type === '搜款搜料') {
    const a = makeAsset(`${task.type === '搜款搜料' ? '候选参考款' : '款式设计参考'} · ${p.name}`, task.type === '搜款搜料' ? '参考资料' : '款式设计', { id: uid(), name: '款式示例.png', date: now(), mime: 'image/png', url: coat }, '任务产出')
    a.taskId = task.id; return a
  }
  const sections = task.type === 'Brief 拆解' ? ['已知需求', '待确认问题：成本、交期、数量与检测要求', '款式与材料约束', '后续行动'] : task.type === '服装企划' ? ['系列主题', '客群与场景', '色彩与面料方向', '款式结构', 'PPT 页面大纲', '内部评审事项'] : task.type === '趋势分析' ? ['资料来源与时间', '趋势观察', '设计转化方向', '证据与待验证事项'] : ['任务目标', '资料与依据', '工作成果', '待人工确认事项']
  const a = makeAsset(`${task.type === '自由任务' ? '任务成果' : task.type}草稿`, '项目文档', { id: uid(), name: `${task.type}-示例草稿.md`, date: now(), mime: 'text/markdown', text: `# ${p.name} · ${task.type}\n\n> 这是原型模板，不是 AI 分析结论；未进行真实检索。请人工编辑补全，或上传正式成果。服装企划此处仅演示大纲，非 PPT 生成。\n\n项目目标：${task.context.goal || '待补充'}\n\n引用资产：${task.refs.map(r => r.name).join('、') || '未引用'}\n\n${sections.map(s => `## ${s}\n\n待补充。`).join('\n\n')}\n` }, '任务产出')
  a.taskId = task.id; return a
}

export function TasksView({ onCaseUpdate, onNavigate, project, activeId, onActive, onCreate, onUpdate, onPatch, onAssets, onRequirements, onOutput, onOpenAsset, onUpload }: { onCaseUpdate: CaseUpdate; onNavigate: (tab: Tab, task?: string) => void; project: Project; activeId: string | null; onActive: (id: string | null) => void; onCreate: () => void; onUpdate: (t: Task) => boolean; onPatch: (id: string, patch: Partial<Task>) => boolean; onAssets: (taskId: string, assets: Asset[], mode: 'collect' | 'design' | 'document') => boolean; onRequirements: (doc: WorkDocument) => boolean; onOutput: (t: Task, a: Asset) => void; onOpenAsset: (id: string) => void; onUpload: (taskId: string) => void }) {
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('全部'), [message, setMessage] = useState('')
  const [capabilityOpen, setCapabilityOpen] = useState(false)
  const [documentEntry, setDocumentEntry] = useState<{ kind: DocumentKind; invocationId?: string } | null>(null)
  const [search, setSearch] = useState<{ kind: SearchSet['kind']; invocationId?: string } | null>(null), [canvasRefs, setCanvasRefs] = useState<Asset[] | null>(null)
  const task = project.tasks.find(t => t.id === activeId)
  const rows = project.tasks.filter(t => t.name.toLowerCase().includes(query.toLowerCase()) && (filter === '全部' || t.status === filter))
  if (!task) return <div className="space-y-5"><div className="flex justify-between gap-3"><div><h2 className="text-[18px] font-semibold">项目任务</h2><p className="text-[12px] text-ink-3 mt-1">围绕同一个目标，发起多个对话，逐步完成开发。</p></div><Button primary onClick={onCreate}><Plus size={15} />新建任务</Button></div><div className="flex justify-between flex-wrap gap-3"><SearchBox value={query} onChange={setQuery} placeholder="搜索任务名称" /><select aria-label="任务状态筛选" className={`${input} !w-auto`} value={filter} onChange={e => setFilter(e.target.value)}>{['全部', ...TASK_STATUSES].map(v => <option key={v}>{v}</option>)}</select></div>
    {!rows.length ? <Empty title="从一个任务开始" text="分析 Brief、研究趋势，或直接整理你的设计想法。" /> : <div className="space-y-3">{rows.map(t => <button key={t.id} onClick={() => { setMessage(''); onActive(t.id) }} className={`${card} p-5 flex w-full text-left items-center gap-4 hover:border-pri/40`}><div className="w-10 h-10 rounded-xl bg-fill-2 flex items-center justify-center shrink-0"><MessageSquare size={18} className="text-ink-3" /></div><div className="min-w-0 flex-1"><h3 className="font-medium truncate" title={t.name}>{t.name}</h3><p className="text-[11px] text-ink-3 mt-2">{t.assignee || project.owner} · {t.type} · {project.assets.filter(a => a.taskId === t.id).length} 项产出 · {dateLabel(t.updated)}</p></div><Badge tone={statusTone(t.status)}>{t.status}</Badge><ArrowUpRight size={16} className="text-mut" /></button>)}</div>}
  </div>
  const outputs = project.assets.filter(a => a.taskId === task.id)
  const canvas = canvasRefs && <ProjectCanvas project={project} task={task} references={canvasRefs} onClose={() => setCanvasRefs(null)} onSaveDraft={r => onPatch(task.id, { canvas: r, updated: now() })} onArchive={assets => onAssets(task.id, assets, 'design')} />
  if (documentEntry) return <DocumentWorkspace key={`${task.id}-${documentEntry.kind}`} kind={documentEntry.kind} invocationId={documentEntry.invocationId} project={project} task={task} onClose={() => setDocumentEntry(null)} onSave={doc => onPatch(task.id, { documents: task.documents?.some(d => d.id === doc.id) ? task.documents.map(d => d.id === doc.id ? doc : d) : [...(task.documents ?? []), doc], updated: now() })} onRequirements={onRequirements} onArchive={assets => onAssets(task.id, assets, 'document')} />
  if (search) return <><SearchWorkspace key={`${task.id}-${search.kind}-${search.invocationId ?? ''}`} project={project} task={task} initialKind={search.kind} invocationId={search.invocationId} onClose={() => setSearch(null)} onCanvas={setCanvasRefs} onCollect={assets => onAssets(task.id, assets, 'collect')} onSave={s => onPatch(task.id, { searches: task.searches?.some(x => x.id === s.id) ? task.searches.map(x => x.id === s.id ? s : x) : [s, ...(task.searches ?? [])], updated: now() })} />{canvas}</>
  if (task.caseStage && task.caseRun) return <><CaseWorkbench key={task.id} project={project} task={task} onUpdate={onCaseUpdate} onBack={() => onActive(null)} onNavigate={onNavigate} onOpenAsset={onOpenAsset} onDocument={kind => setDocumentEntry({ kind })} onCanvas={setCanvasRefs} onUpload={() => onUpload(task.id)} onSaveTask={onUpdate} />{canvas}</>
  return <div className="space-y-5"><button onClick={() => onActive(null)} className="flex items-center gap-2 text-ink-3 hover:text-pri text-[12px]"><ArrowLeft size={14} />全部任务</button><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="text-[18px] font-semibold break-words">{task.name}</h2><p className="text-[11px] text-ink-3 mt-2">{task.type} · {dateLabel(task.updated)}</p></div><Badge tone={statusTone(task.status)}>{task.status}</Badge></div>
    <TaskLifecycle project={project} task={task} onSave={onUpdate} />
    <details className="border border-line rounded-xl px-4 py-3 text-[12px]"><summary className="cursor-pointer text-ink-3">项目背景与引用 · {task.refs.length} 份资产</summary><p className="mt-3 whitespace-pre-wrap leading-6">{task.context.goal || '未设置项目目标'}</p><p className="mt-2 text-ink-3">客户：{task.context.customers.join('、') || '自主开发'} · 品牌：{task.context.brands.join('、') || '未关联'}</p><p className="mt-2 text-ink-3">专家：{task.context.experts.join('、') || '未配置'}<br />技能：{task.context.skills.join('、') || '未配置'}<br />拟接入：{task.context.connectors.join('、') || '未配置'}</p><div className="flex flex-wrap gap-2 mt-3">{task.refs.map(r => <span key={r.assetId} className="px-3 py-1 rounded-full bg-fill">{r.name}</span>)}</div><p className="mt-3 text-[11px] text-mut">这是创建时的上下文快照，不会自动读取其他对话全文或外部系统。</p>{task.context.requirements && <details className="mt-3"><summary className="cursor-pointer text-ink">已确认项目需求：{task.context.requirements.title}</summary><div className="space-y-3 mt-3">{task.context.requirements.sections.map(s => <div key={s.id}><p className="font-medium">{s.title}</p><p className="whitespace-pre-wrap break-words">{s.body || '待补充'}</p></div>)}</div></details>}<ProfileSnapshots profiles={task.context.profiles} /></details>
    {!!task.context.teams?.length && <p className="text-[12px] text-ink-3">任务创建时的专家团：{task.context.teams.join('、')}</p>}
    <div className="space-y-5">{task.messages.map(m => <div key={m.id} className={`flex gap-3 ${m.role === 'user' ? 'justify-end' : ''}`}>{m.role === 'assistant' && <div className="shrink-0 rounded-full bg-pri-soft text-pri w-8 h-8 flex items-center justify-center"><Sparkles size={15} /></div>}<div className={`max-w-[90%] rounded-2xl px-4 py-3 text-[13px] leading-7 whitespace-pre-wrap break-words ${m.role === 'user' ? 'bg-fill text-ink' : 'bg-panel border border-line'}`}>{m.text}</div></div>)}</div>
    <DemoTaskFlow key={`${task.id}-${task.demoRun?.request ?? ''}-${task.demoRun?.scenario ?? ''}`} task={task} project={project} onPatch={patch => onPatch(task.id, patch)} onOutput={onOutput} onOpenAsset={onOpenAsset} onDocument={kind => setDocumentEntry({ kind })} onSearch={() => setSearch({ kind: '款式' })} />
    <InvocationCards onDocument={(kind, invocationId) => setDocumentEntry({ kind, invocationId })} task={task} onOutput={onOutput} onOpenAsset={onOpenAsset} onSearch={(kind, invocationId) => setSearch({ kind, invocationId })} />
    <div className="flex flex-wrap gap-2"><Button onClick={() => setSearch({ kind: '款式' })}>搜款搜料{task.searches?.length ? ` · ${task.searches.length} 个结果集` : ''}</Button><Button onClick={() => setCanvasRefs(task.refs.flatMap(r => { const a = project.assets.find(a => a.id === r.assetId); return a && a.revisions.find(v => v.id === r.revisionId)?.mime.startsWith('image/') ? [{ ...a, adopted: r.revisionId }] : [] }))}>{task.canvas ? '继续设计画布' : '打开设计画布'}</Button></div>
    <div className="flex flex-wrap items-center gap-2"><span className="text-[12px] text-ink-3 mr-1">工作稿</span>{(['Brief 拆解', '趋势报告', '企划 PPT'] as DocumentKind[]).map(kind => <Button key={kind} onClick={() => setDocumentEntry({ kind })}>{kind}{task.documents?.some(d => d.kind === kind) ? ' · 继续编辑' : ''}</Button>)}</div>
    {canvas}
    <div><Button onClick={() => setCapabilityOpen(true)}><Sparkles size={15} />调用技能 / 专家 / 专家团</Button></div>
    {capabilityOpen && <CapabilityPicker project={project} task={task} onClose={() => setCapabilityOpen(false)} onSave={invocation => onUpdate({ ...task, updated: now(), status: '进行中', invocations: [...(task.invocations ?? []), invocation] })} />}
    {outputs.length > 0 && <div className={`${card} p-4`}><h3 className="font-medium flex items-center gap-2 mb-3"><Check size={15} className="text-pri" />已归档的任务产出</h3><div className="space-y-2">{outputs.map(a => <button key={a.id} onClick={() => onOpenAsset(a.id)} className="w-full flex items-center gap-3 text-left p-3 rounded-xl bg-fill-2 hover:bg-fill"><FileText size={17} className="text-ink-3 shrink-0" /><span className="flex-1 truncate" title={a.name}>{a.name}</span><span className="text-[11px] text-mut">{adopted(a).name.split('.').pop()?.toUpperCase()}</span><ArrowUpRight size={14} /></button>)}</div></div>}
    <div className="flex flex-wrap gap-2"><Button onClick={() => { const a = sampleOutput(task, project); onOutput({ ...task, status: '待人工处理', updated: now(), messages: [...task.messages, { id: uid(), role: 'assistant', text: `【原型演示】已归档「${a.name}」。这是预置示例，不是真实 AI 生成或检索结果；请在资产中预览、下载或上传修订。`, date: now() }] }, a) }}>演示产出并归档</Button><Button onClick={() => onUpload(task.id)}>上传人工成果</Button></div>
    <form className={`${card} p-4`} onSubmit={e => { e.preventDefault(); if (!message.trim()) return; onUpdate({ ...task, demoRun: demoRequest(message.trim()), status: '进行中', updated: now(), messages: [...task.messages, { id: uid(), role: 'user', text: message.trim(), date: now() }, { id: uid(), role: 'assistant', text: '我先整理了这次任务的执行方向。你可以补充要求，确认后查看专家协作与成果归档的演示。', date: now() }] }); setMessage('') }}><textarea aria-label="继续任务对话" className="w-full bg-transparent resize-none outline-none text-[13px] leading-6 placeholder:text-mut-2" rows={3} maxLength={10000} value={message} onChange={e => setMessage(e.target.value)} placeholder="继续补充要求、讨论或记录修改意见…" /><div className="flex items-center justify-between gap-4 mt-2"><span className="text-[11px] text-mut">原型对话 · 未连接 AI 服务</span><Button primary type="submit" disabled={!message.trim()} aria-label="发送消息" title="发送" className="w-9 px-0"><ArrowUp size={17} /></Button></div></form>
  </div>
}
