const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
const base = process.env.PROJECT_TEST_URL || 'http://127.0.0.1:4173'
const out = '/Users/mac/Desktop/迪尚ODM/tmp/directory-module-check'
let count = 0
function check(value, name) { assert.ok(value, name); console.log('PASS', name); count++ }
;(async () => {
  await fs.mkdir(out, { recursive: true })
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
  const page = await context.newPage(), errors = []
  page.on('pageerror', e => errors.push(e.message))
  const directory = () => page.evaluate(() => JSON.parse(localStorage.getItem('hyy-odm-directory-v1')).records)
  const projects = () => page.evaluate(() => JSON.parse(localStorage.getItem('hyy-odm-projects-v1')))
  const close = () => page.keyboard.press('Escape')
  try {
    await page.goto(`${base}/?view=customers`)
    await page.getByRole('heading', { name: '客户档案', exact: true }).waitFor()
    await page.screenshot({ path: path.join(out, '01-customers.png') })
    await page.getByRole('button', { name: '新建客户', exact: true }).click()
    let modal = page.getByRole('dialog')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    check((await modal.getByRole('alert').innerText()).includes('名称'), 'customer name required')
    await modal.getByLabel('客户名称 *', { exact: true }).fill('测试客户 A')
    await modal.getByLabel('联系人 / 联系方式', { exact: true }).fill('私有联系人，不应自动带入任务')
    await modal.getByLabel('业务负责人', { exact: true }).fill('李经理')
    await modal.getByLabel('常用品类', { exact: true }).fill('风衣、夹克')
    await modal.getByLabel('开发要求 / 风格偏好', { exact: true }).fill('首轮轻量风衣开发，成本上限待确认。')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    await page.getByRole('heading', { name: '测试客户 A', exact: true }).waitFor()
    const customerId = (await directory()).find(r => r.name === '测试客户 A').id
    const customerURL = page.url()
    const bytes = Buffer.from('客户 Brief：成本与交期必须内部确认。')
    await page.getByLabel('上传档案资料', { exact: true }).setInputFiles({ name: '客户Brief.txt', mimeType: 'text/plain', buffer: bytes })
    await page.getByRole('button', { name: '下载 客户Brief.txt', exact: true }).waitFor()
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '下载 客户Brief.txt', exact: true }).click()
    check((await fs.readFile(await (await downloadPromise).path())).equals(bytes), 'profile document uploads and downloads original bytes')
    await page.reload()
    await page.getByRole('button', { name: '下载 客户Brief.txt', exact: true }).waitFor()
    check((await directory()).find(r => r.id === customerId).documents.length === 1, 'profile metadata and files persist')
    await page.screenshot({ path: path.join(out, '02-customer-detail.png') })
    await page.getByRole('navigation').getByRole('button', { name: '品牌库', exact: true }).click()
    await page.getByRole('heading', { name: '品牌档案', exact: true }).waitFor()
    await page.getByRole('button', { name: '新建品牌', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('品牌名称 *', { exact: true }).fill('STUDIO A')
    await modal.getByLabel('品牌定位', { exact: true }).fill('轻量都市户外')
    await modal.getByLabel('目标客群', { exact: true }).fill('城市通勤人群')
    await modal.getByLabel('风格偏好', { exact: true }).fill('简洁、自然')
    await modal.getByRole('button', { name: '测试客户 A', exact: true }).click()
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    await page.getByRole('heading', { name: 'STUDIO A', exact: true }).waitFor()
    const brandId = (await directory()).find(r => r.name === 'STUDIO A').id
    const brandURL = page.url()
    check((await directory()).find(r => r.id === brandId).customerIds.includes(customerId), 'brand-customer relationship stored by stable ID')
    await page.screenshot({ path: path.join(out, '03-brand-detail.png') })
    await page.getByRole('link', { name: /基于此品牌建项目/ }).click()
    modal = page.getByRole('dialog')
    check(await modal.getByRole('button', { name: 'STUDIO A', exact: true }).getAttribute('aria-pressed') === 'true', 'new project from brand preselects brand')
    check(await modal.getByRole('button', { name: '测试客户 A', exact: true }).getAttribute('aria-pressed') === 'false', 'brand association does not silently force customer association')
    await close()
    await page.goto(customerURL)
    await page.getByRole('link', { name: /基于此客户建项目/ }).click()
    modal = page.getByRole('dialog')
    check(await modal.getByRole('button', { name: '测试客户 A', exact: true }).getAttribute('aria-pressed') === 'true', 'new project from customer preselects customer')
    check(await modal.getByText('根据所选客户推荐', { exact: true }).isVisible(), 'customer selection recommends related brands')
    await modal.getByRole('button', { name: 'STUDIO A', exact: true }).click()
    await modal.getByLabel('项目名称 *', { exact: true }).fill('串联验证项目')
    await modal.getByRole('button', { name: '创建项目', exact: true }).click()
    await page.getByRole('heading', { name: '串联验证项目', exact: true }).waitFor()
    const projectId = new URL(page.url()).searchParams.get('project'), projectURL = page.url()
    const readProject = async () => (await projects()).find(p => p.id === projectId)
    check((await readProject()).customerIds[0] === customerId && (await readProject()).brandIds[0] === brandId, 'project stores canonical customer and brand IDs')
    await page.getByRole('button', { name: '新建任务', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('这次需要完成什么？ *', { exact: true }).fill('先独立讨论，不读取客户档案')
    await modal.getByRole('button', { name: '创建任务', exact: true }).click()
    check((await readProject()).tasks[0].context.profiles.length === 0, 'profiles are opt-in, not automatically read')
    await page.getByRole('tab', { name: '任务', exact: true }).click()
    await page.getByRole('button', { name: '新建任务', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.locator('summary').filter({ hasText: '引用客户 / 品牌资料' }).click()
    await modal.getByRole('checkbox', { name: '客户背景：测试客户 A', exact: true }).check()
    await modal.getByRole('checkbox', { name: '品牌背景：STUDIO A', exact: true }).check()
    await modal.getByLabel('引用文件 客户Brief.txt', { exact: true }).check()
    await modal.getByLabel('这次需要完成什么？ *', { exact: true }).fill('结合已选客户和品牌背景，做需求拆解')
    await modal.getByRole('button', { name: '创建任务', exact: true }).click()
    const taskSnapshot = JSON.stringify((await readProject()).tasks[0].context.profiles)
    check(JSON.parse(taskSnapshot).length === 2 && JSON.parse(taskSnapshot)[0].documents.length === 1, 'explicit profiles and file references captured in task')
    check(!taskSnapshot.includes('私有联系人'), 'contact details excluded from AI background summary')
    await page.goto(customerURL)
    await page.getByRole('button', { name: '编辑档案', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('客户名称 *', { exact: true }).fill('测试客户 A（更名）')
    await modal.getByLabel('开发要求 / 风格偏好', { exact: true }).fill('新方向：户外夹克。')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    await page.getByRole('heading', { name: '测试客户 A（更名）', exact: true }).waitFor()
    check(await page.getByRole('link', { name: /串联验证项目/ }).isVisible(), 'renamed customer keeps reverse project association')
    await page.getByRole('link', { name: /串联验证项目/ }).click()
    await page.getByRole('link', { name: /测试客户 A（更名）/ }).waitFor()
    check((await readProject()).customerIds[0] === customerId, 'rename preserves stable customer ID on project')
    check(JSON.stringify((await readProject()).tasks[0].context.profiles) === taskSnapshot, 'profile edits never mutate existing task snapshot')
    await page.goto(brandURL)
    await page.getByRole('button', { name: '编辑档案', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('品牌名称 *', { exact: true }).fill('STUDIO A NEW')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    await page.goto(projectURL)
    await page.getByRole('link', { name: /STUDIO A NEW/ }).waitFor()
    check((await readProject()).brandIds[0] === brandId, 'brand rename preserves project link')
    await page.goto(`${base}/?view=customers`)
    await page.getByRole('button', { name: '新建客户', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('客户名称 *', { exact: true }).fill('测试客户 A')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    check((await modal.getByRole('alert').innerText()).includes('历史名称'), 'duplicate former names rejected to protect legacy associations')
    await close()
    // Inject a legacy project in this isolated test context only, then check migration.
    await page.evaluate(() => {
      const ps = JSON.parse(localStorage.getItem('hyy-odm-projects-v1'))
      const legacy = structuredClone(ps[0]); legacy.id = 'legacy-project-test'; legacy.name = '旧版本项目'; legacy.customers = ['旧客户']; legacy.brands = ['旧品牌']; delete legacy.customerIds; delete legacy.brandIds
      legacy.pushes = [{ id: 'legacy-push', customer: '旧客户', date: new Date().toISOString(), items: [], feedback: '旧反馈应保留' }]
      localStorage.setItem('hyy-odm-projects-v1', JSON.stringify([...ps, legacy]))
    })
    await page.reload()
    await page.getByRole('button', { name: /旧客户/ }).click()
    await page.getByRole('heading', { name: '旧客户', exact: true }).waitFor()
    await page.getByText('旧反馈应保留', { exact: true }).waitFor()
    check(await page.getByText('旧反馈应保留', { exact: true }).isVisible(), 'legacy names and customer feedback imported without losing history')
    await page.getByRole('button', { name: '编辑档案', exact: true }).click()
    modal = page.getByRole('dialog')
    await modal.getByLabel('客户名称 *', { exact: true }).fill('旧客户新名字')
    await modal.getByRole('button', { name: '保存档案', exact: true }).click()
    await page.getByRole('heading', { name: '旧客户新名字', exact: true }).waitFor()
    await page.getByText('旧反馈应保留', { exact: true }).waitFor()
    check(await page.getByText('旧反馈应保留', { exact: true }).isVisible(), 'legacy feedback survives rename before project is re-saved')
    await page.getByRole('link', { name: /旧版本项目/ }).click()
    await page.getByRole('link', { name: /旧客户新名字/ }).waitFor()
    check((await projects()).find(p => p.id === 'legacy-project-test').customerIds.length === 1, 'legacy project upgraded to ID associations without changing its outputs')
    await page.getByRole('navigation').getByRole('button', { name: '品牌库', exact: true }).click()
    await page.getByRole('tab', { name: '原有资产库', exact: true }).click()
    await page.getByRole('heading', { name: '品牌库', exact: true }).waitFor()
    check(await page.getByText('品牌款式库', { exact: true }).isVisible(), 'original brand asset library remains accessible')
    await page.getByRole('tab', { name: '品牌档案', exact: true }).click()
    await page.getByRole('heading', { name: '品牌档案', exact: true }).waitFor()
    await page.screenshot({ path: path.join(out, '04-brand-list.png') })
    await page.getByLabel('搜索品牌档案', { exact: true }).fill('找不到这个品牌')
    check(await page.getByText('暂无匹配的品牌', { exact: true }).isVisible(), 'directory search empty state')
    check(errors.length === 0, `no runtime errors: ${errors.join('; ')}`)
    console.log(`COMPLETE: ${count} directory checks`)
  } catch (e) { await page.screenshot({ path: path.join(out, 'failure.png') }); console.error((await page.locator('body').innerText()).slice(-4000)); throw e } finally { await browser.close() }
})().catch(e => { console.error(e); process.exitCode = 1 })
