/* Project-module browser checks. Uses a fresh browser context; no user data is touched.
 * PROJECT_TEST_URL defaults to the running Vite server. PLAYWRIGHT_MODULE and
 * CHROME_PATH can override the local runtime paths for another workstation.
 */
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '/Users/mac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
const base = process.env.PROJECT_TEST_URL || 'http://127.0.0.1:4173'
const out = process.env.PROJECT_TEST_OUTPUT || '/Users/mac/Desktop/迪尚ODM/tmp/project-module-check'
const errors = []
let assertions = 0
function check(value, message) { assert.ok(value, message); assertions++; console.log('PASS', message) }
;(async () => {
  await fs.mkdir(out, { recursive: true })
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' })
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
    const page = await context.newPage()
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
    await page.goto(`${base}/?view=projects`)
    await page.getByRole('heading', { name: '项目', exact: true }).waitFor()
    await page.screenshot({ path: path.join(out, '01-project-list.png') })
    await page.getByRole('button', { name: /2026 夏季轻量风衣/ }).click()
    await page.getByRole('tab', { name: '概览', exact: true }).waitFor()
    check(await page.getByRole('tab').allTextContents().then(v => v.join('、') === '概览、任务、资产、交付'), 'exact four tabs')
    await page.screenshot({ path: path.join(out, '02-overview.png') })
    await page.getByRole('tab', { name: '资产', exact: true }).click()
    await page.getByRole('heading', { name: /项目资产/ }).waitFor()
    await page.screenshot({ path: path.join(out, '03-assets.png') })
    await page.getByRole('tab', { name: '交付', exact: true }).click()
    await page.getByRole('heading', { name: '项目交付', exact: true }).waitFor()
    await page.screenshot({ path: path.join(out, '04-delivery.png') })
    await page.getByRole('button', { name: '内部确认与交接', exact: true }).click()
    let dialog = page.getByRole('dialog')
    check(await dialog.getByRole('button', { name: '确认并模拟交接' }).isDisabled(), 'handoff requires explicit internal confirmation')
    check(!(await dialog.getByText('松弛感长款风衣', { exact: true }).count()), 'needs-revision style excluded from handoff')
    await page.keyboard.press('Escape')
    await page.getByRole('navigation').getByRole('button', { name: '项目', exact: true }).click()
    await page.getByRole('button', { name: '新建项目', exact: true }).click()
    dialog = page.getByRole('dialog')
    await page.screenshot({ path: path.join(out, '05-create.png') })
    await dialog.getByRole('button', { name: '创建项目', exact: true }).click()
    check(await dialog.getByRole('alert').isVisible(), 'blank project rejected')
    await dialog.getByLabel('项目名称 *', { exact: true }).fill('测试项目 · 夏季风衣')
    await dialog.getByLabel('项目目标 / 指令', { exact: true }).fill('为都市通勤开发轻量风衣，先自主开发，再向客户推广。')
    await dialog.getByLabel('季节', { exact: true }).fill('2026 春夏')
    await dialog.getByLabel('品类', { exact: true }).fill('风衣')
    await dialog.getByRole('button', { name: '创建项目', exact: true }).click()
    await page.getByRole('heading', { name: '测试项目 · 夏季风衣', exact: true }).waitFor()
    const projectURL = page.url()
    const projectID = new URL(projectURL).searchParams.get('project')
    const read = () => page.evaluate(id => JSON.parse(localStorage.getItem('hyy-odm-projects-v1')).find(p => p.id === id), projectID)
    check((await read()).customers.length === 0, 'autonomous project needs no customer')
    await page.reload()
    await page.getByRole('heading', { name: '测试项目 · 夏季风衣', exact: true }).waitFor()
    check(page.url() === projectURL, 'project survives reload with deep link')
    await page.getByRole('button', { name: '编辑项目配置', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.locator('summary').filter({ hasText: '技能' }).click()
    await dialog.getByRole('button', { name: '系列企划生成', exact: true }).click()
    await dialog.getByRole('button', { name: '保存配置', exact: true }).click()
    check((await read()).skills.includes('系列企划生成'), 'project skill configuration saved')
    await page.getByRole('button', { name: '新建任务', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('任务类型', { exact: true }).selectOption('Brief 拆解')
    await dialog.getByLabel('任务名称（可选）', { exact: true }).fill('需求分析测试')
    await dialog.getByLabel('这次需要完成什么？ *', { exact: true }).fill('帮我整理需要确认的风衣需求。')
    await dialog.getByRole('button', { name: '创建任务', exact: true }).click()
    await page.getByRole('heading', { name: '需求分析测试', exact: true }).waitFor()
    check((await read()).tasks[0].context.skills.includes('系列企划生成'), 'task records project context snapshot')
    await page.getByLabel('继续任务对话', { exact: true }).fill('请把面料采购条件也列为待确认事项。')
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    check((await read()).tasks[0].messages.length === 4, 'multi-round conversation persists')
    await page.getByRole('button', { name: '演示产出并归档', exact: true }).click()
    const outputAsset = (await read()).assets[0]
    check(outputAsset.taskId === (await read()).tasks[0].id, 'task output archived to same project')
    await page.screenshot({ path: path.join(out, '06-task.png') })
    await page.getByRole('button', { name: /Brief 拆解草稿 MD/ }).click()
    dialog = page.getByRole('dialog')
    let downloadEvent = page.waitForEvent('download')
    await dialog.getByRole('button', { name: '下载此版本', exact: true }).click()
    let download = await downloadEvent
    check((await fs.readFile(await download.path(), 'utf8')).includes('不是 AI 分析结论'), 'actual original download bytes')
    const revised = '# 人工修订\n\n已补充面料采购条件：先核实供应商与可采购量。'
    await dialog.getByLabel('上传新版本文件', { exact: true }).setInputFiles({ name: '人工修订.md', mimeType: 'text/markdown', buffer: Buffer.from(revised) })
    await dialog.getByRole('button', { name: '采用此版本', exact: true }).waitFor()
    let assetState = (await read()).assets.find(a => a.id === outputAsset.id)
    check(assetState.revisions.length === 2 && assetState.adopted === outputAsset.adopted, 'upload does not auto-adopt new revision')
    await dialog.getByRole('button', { name: '采用此版本', exact: true }).click()
    await dialog.getByRole('button', { name: '选入交付', exact: true }).click()
    await page.keyboard.press('Escape')
    await page.reload()
    await page.getByRole('heading', { name: '需求分析测试', exact: true }).waitFor()
    await page.getByRole('button', { name: /Brief 拆解草稿 MD/ }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByText(/已补充面料采购条件/).waitFor()
    downloadEvent = page.waitForEvent('download')
    await dialog.getByRole('button', { name: '下载此版本', exact: true }).click()
    download = await downloadEvent
    check((await fs.readFile(await download.path(), 'utf8')) === revised, 'revised file survives reload and downloads exact bytes')
    await dialog.getByRole('button', { name: '引用已采用版本到任务', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('这次需要完成什么？ *', { exact: true }).fill('根据已经确认的需求继续做企划。')
    await dialog.getByRole('button', { name: '创建任务', exact: true }).click()
    const pAfterRef = await read()
    check(pAfterRef.tasks.length === 2 && pAfterRef.tasks[0].refs[0].revisionId === pAfterRef.assets.find(a => a.id === outputAsset.id).adopted, 'many tasks per project; adopted version explicitly referenced')
    await page.getByRole('tab', { name: '资产', exact: true }).click()
    await page.getByRole('button', { name: '上传资产', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('资产分类', { exact: true }).selectOption('款式设计')
    await dialog.getByLabel('选择上传文件', { exact: true }).setInputFiles(path.resolve(__dirname, '../src/assets/brandlib/coat1.png'))
    await dialog.getByRole('button', { name: '上传 1 个文件', exact: true }).click()
    await page.getByRole('button', { name: /coat1 款式设计/ }).waitFor()
    await page.getByRole('button', { name: /coat1 款式设计/ }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('面辅料选择 / 样衣开发说明', { exact: true }).fill('面料 A-001，棉锦混纺；纽扣 T-02；首轮样衣 1 件。')
    await dialog.getByLabel('凌迪 Cloud 3D 样衣链接（可选）', { exact: true }).fill('javascript:alert(1)')
    await dialog.getByRole('button', { name: '保存开发说明', exact: true }).click()
    check(!(await read()).assets[0].cloud, 'unsafe 3D link rejected')
    await dialog.getByLabel('凌迪 Cloud 3D 样衣链接（可选）', { exact: true }).fill('https://cloud.style3d.com/')
    await dialog.getByRole('button', { name: '保存开发说明', exact: true }).click()
    await dialog.getByRole('button', { name: '选入交付', exact: true }).click()
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: '交付', exact: true }).click()
    check(await page.getByRole('button', { name: '内部确认与交接', exact: true }).isDisabled(), 'unselected style cannot be handed off')
    await page.getByLabel('coat1内部选款', { exact: true }).selectOption('保留')
    await page.getByRole('button', { name: '内部确认与交接', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByRole('checkbox').last().check()
    await dialog.getByRole('button', { name: '确认并模拟交接', exact: true }).click()
    const snap = JSON.stringify((await read()).handoffs[0])
    check((await read()).handoffs[0].items.length === 2, 'internal confirmation fixes selected document and style snapshot')
    await page.getByRole('button', { name: '查看 / 补充开发资料', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('面辅料选择 / 样衣开发说明', { exact: true }).fill('交接后调整为面料 B-002。')
    await dialog.getByRole('button', { name: '保存开发说明', exact: true }).click()
    await page.keyboard.press('Escape')
    check(JSON.stringify((await read()).handoffs[0]) === snap, 'later asset edits do not mutate historical handoff')
    await page.getByRole('button', { name: '编辑信息', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByRole('button', { name: '北辰服饰（示例）', exact: true }).click()
    await dialog.getByRole('button', { name: '远山户外（示例）', exact: true }).click()
    await dialog.getByRole('button', { name: '保存修改', exact: true }).click()
    check((await read()).customers.length === 2, 'project supports multiple optional customers')
    await page.getByRole('button', { name: '新建推款记录', exact: true }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByRole('button', { name: '保存推款记录', exact: true }).click()
    await page.getByRole('button', { name: /北辰服饰（示例）.*待反馈/ }).click()
    dialog = page.getByRole('dialog')
    await dialog.getByLabel('客户反馈', { exact: true }).fill('喜欢廓形，请调整为更轻的面料。')
    await dialog.getByRole('button', { name: '保存反馈', exact: true }).click()
    check((await read()).pushes[0].feedback.includes('更轻的面料') && JSON.stringify((await read()).handoffs[0]) === snap, 'customer feedback saved without authorizing or changing handoff')
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: '概览', exact: true }).click()
    await page.getByLabel('项目留言', { exact: true }).fill('内部讨论：继续完善资料。')
    await page.getByRole('button', { name: '发布', exact: true }).click()
    check((await read()).activities[0].text.includes('内部讨论'), 'project comments saved')
    await page.getByRole('button', { name: '标记为已归档', exact: true }).click()
    check((await read()).status === '已归档', 'archive is reversible and preserves data')
    await page.getByRole('button', { name: '重新启用项目', exact: true }).click()
    await page.evaluate(() => document.documentElement.dataset.theme = 'dark')
    await page.locator('main').evaluate(el => el.scrollTo(0, 0))
    await page.waitForTimeout(300)
    await page.screenshot({ path: path.join(out, '07-dark.png') })
    await page.evaluate(() => delete document.documentElement.dataset.theme)
    for (const width of [1280, 1024]) {
      await page.setViewportSize({ width, height: 900 })
      const collapse = page.getByRole('button', { name: '收起项目配置', exact: true })
      if (await collapse.count()) await collapse.click()
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `no document horizontal overflow at ${width}px`)
      await page.screenshot({ path: path.join(out, `08-width-${width}.png`) })
    }
    await page.getByRole('button', { name: '品牌库', exact: true }).click()
    await page.getByRole('heading', { name: '品牌档案', exact: true }).waitFor()
    await page.getByRole('tab', { name: '原有资产库', exact: true }).click()
    await page.getByRole('heading', { name: '品牌库', exact: true }).waitFor()
    check(!(await page.getByTestId('projects-module').count()), 'existing brand module remains accessible')
    await page.getByRole('navigation').getByRole('button', { name: '项目', exact: true }).click()
    await page.getByRole('heading', { name: '项目', exact: true }).waitFor()
    await page.getByLabel('搜索项目、客户或品牌', { exact: true }).fill('不存在的项目')
    check(await page.getByText('没有匹配的项目，可以调整筛选或新建项目。').isVisible(), 'project search empty state')
    check(errors.length === 0, `no runtime errors: ${errors.join('; ')}`)
    console.log(`COMPLETE: ${assertions} checks. Screenshots: ${out}`)
  } catch (error) {
    const pages = browser.contexts()[0]?.pages() ?? []
    if (pages[0]) { await pages[0].screenshot({ path: path.join(out, 'failure.png') }); console.error((await pages[0].locator('body').innerText()).slice(-6000)) }
    throw error
  } finally { await browser.close() }
})().catch(e => { console.error(e); process.exitCode = 1 })
